# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
name: Dependabot Auto-Merge

on:
  pull_request_target:
    types:
      - opened
      - synchronize

permissions:
  pull-requests: write

version: 1
updates:
  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"

jobs:
  auto_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Auto-merge Dependabot PR
        if: github.actor == 'dependabot[bot]'
        run: |
          # Approve the PR
          gh pr review --approve ${{ github.event.number }}

          # Merge the PR
          gh pr merge --auto ${{ github.event.number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
